# Generated by Django 4.0.3 on 2023-09-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_customer_customer_id_alter_automobilevo_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
    ]
